function orgt(s){ return binl2hex(core_hx(str2binl(s), s.length * chrsz));}
var bookConfig={DownloadButtonVisible: "Hide",BookmarkButtonVisible : "Hide",
searchColor : "#00ffff", searchAlpha : 0.3, leastSearchChar : 0,CreatedBy:"Litoempaques",
CreatedTime:"20181022095916",BookTemplateName:"Metro",loadingBackground:"#ADADAD",
searchPositionJS:"files/search/text_position[%d].js",loadingCaptionColor:"#DDDDDD",
loadingBackground:"#1F2232",loadingPicture:"",bgBeginColor:"#1F2232",bgEndColor:"#1F2232",
bgMRotation:90,backGroundImgURL:"files/extfile/bg.jpg",backgroundPosition:"Stretch",backgroundOpacity:100,
backgroundScene:"None",LeftShadowWidth:100,LeftShadowAlpha:1,RightShadowWidth:40,RightShadowAlpha:1,
pageBackgroundColor:"#FFFFFF",flipshortcutbutton:"Hide",OriginPageIndex:1,thicknessWidthType:"thick",
thicknessColor:"#FFFFFF",showThicknessOnMobile:"No",HardPageEnable:"No",hardCoverBorderWidth:8,cornerRound:8,
borderColor:"#000000",outerCoverBorder:"No",coverTexture:"none",HardInnerPageEnable:"No",
showGotoButtonsAtFirst:"No",highDefinitionConversion:"No",RightToLeft:"No",retainBookCenter:"Yes",
isTheBookOpen:"No",FlipStyle:"Catalog",FlipDirection:"0",totalPagesCaption:"",pageNumberCaption:"",
topMargin:0,bottomMargin:5,leftMargin:10,rightMargin:10,leftMarginOnMobile:0,topMarginOnMobile:0,rightMarginOnMobile:0,
bottomMarginOnMobile:0,bleedAreaLeft:"0%",bleedAreaTop:"0%",bleedAreaRight:"0%",bleedAreaBottom:"0%",ToolbarViewMode:"Hide",
appLogoIcon:"",appLogoLinkURL:"",appLogoOpenWindow:"Blank",bookTitle:"Catalogo 2018",
bookDescription:"Catálogo 2018",toolbarColor:"#000000",iconColor:"#EEEEEE",iconFontColor:"#EEEEEE",pageNumColor:"#111111",
formBackgroundColor:"#000000",formFontColor:"#EEEEEE",QRCode:"Hide",logoHeight:0,logoPadding:0,logoTop:0,
HomeButtonVisible:"Hide",HomeURL:"%first page%",HomeButtonIcon:"",AnnotationButtonVisible:"Hide",AnnotationButtonIcon:"",
ShareButtonVisible:"Hide",ShareButtonIcon:"",addCurrentPage:"Hide",isInsertFrameLinkEnable:"Hide",facebookShotImageURL:"",
ThumbnailsButtonVisible:"Hide",ThumbnailButtonIcon:"",ZoomButtonVisible:"Hide",ZoomInButtonIcon:"",ZoomOutButtonIcon:"",
FullscreenButtonVisible:"Hide",FullscreenButtonIcon:"",ExitFullscreenButtonIcon:"",TableOfContentButtonVisible:"Hide",
isHideTabelOfContentNodes:"Yes",BookmarkButtonIcon:"",SearchButtonVisible:"Hide",leastSearchChar:3,
searchKeywordFontColor:"#FFB000",searchHightlightColor:"#FDC606",SearchButtonIcon:"",SelectTextButtonVisible:"Hide",
SelectTextButtonIcon:"",PrintButtonVisible:"Hide",PrintButtonIcon:"",printWatermarkFile:"",BackgroundSoundButtonVisible:"Hide",
BackgroundSoundURL:"",BackgroundSoundLoop:-1,BackgroundSoundButtonOnIcon:"",BackgroundSoundButtonOffIcon:"",
HelpButtonVisible:"Hide",helpContentFileURL:"",helpWidth:400,helpHeight:450,showHelpContentAtFirst:"No",HelpButtonIcon:"No",
InstructionsButtonVisible:"Hide",showInstructionOnStart:"No",aboutButtonVisible:"hide",CompanyLogoFile:"",AboutButtonIcon:"",
AutoPlayButtonVisible:"Hide",autoPlayAutoStart:"Yes",autoPlayDuration:3,autoPlayLoopCount:1,AutoPlayStartButtonIcon:"",
AutoPlayStopButtonIcon:"",minZoomWidth:403,minZoomHeight:518,DownloadButtonVisible:"Show",DownloadButtonIcon:"",
DownloadURL:"../portafolio/portafolio.pdf",VideoButtonVisible:"Hide",VideoButtonIcon:"",SlideshowButtonVisible:"Hide",SlideshowButtonIcon:"",
PhoneButtonVisible:"Hide",PhoneButtonIcon:"",FlipSound:"No",flippingTime:0.6,mouseWheelFlip:"No",
CurlingPageCorner:"Yes",updateURLForPage:"Yes",isStopMouseMenu:"Yes",OpenWindow:"Blank",showLinkHint:"No",
haveAdSense:"No",adSenseWidth:200,adSenseHeight:200,adSenseLeft:50,adSenseTop:50,adSenseClientId:"",googleAnalyticsID:"",
language: "English",AboutAddress: "Calle 2 # 50 - 383 - Medellín - Colombia",AboutEmail: "practsistemas@litoempaques.com",AboutMobile: "57(4) 352-95-78",
AboutWebsite: "http://www.litoempaques.com",AboutDescription: "Litoempaques es una empresa que pertenece al grupo COMECA, líder multilatina en fabricación de soluciones de empaque. Somos expertos en el desarrollo y la fabricación de impresiones litográficas y ensamble de envases en hojalata para usos decorativos, publicitarios e industriales. Contamos con la experiencia necesaria para llevar a la realidad ideas de empaque que generan valor agregado a los productos, con procesos confiables y los mejores materiales.",AboutAuthor: "Litoempaques",
SlideshowAutoPlay: false,SlideshowPlayInterval: 5,totalPageCount:40,largePageWidth:2200,largePageHeight:1700,
normalPath:"files/page/",largePath:"files/large/",thumbPath:"files/thumb/"}
var fliphtml5_pages=[{"l":"files/page/1.jpg", "n":"files/page/1.jpg", "t":"files/thumb/1.jpg"},
{"l":"files/page/2.jpg", "n":"files/page/2.jpg", "t":"files/thumb/2.jpg"},{"l":"files/page/3.jpg",
"n":"files/page/3.jpg", "t":"files/thumb/3.jpg"},{"l":"files/page/4.jpg", "n":"files/page/4.jpg",
"t":"files/thumb/4.jpg"},{"l":"files/page/5.jpg", "n":"files/page/5.jpg", "t":"files/thumb/5.jpg"},
{"l":"files/page/6.jpg", "n":"files/page/6.jpg", "t":"files/thumb/6.jpg"},{"l":"files/page/7.jpg",
"n":"files/page/7.jpg", "t":"files/thumb/7.jpg"},{"l":"files/page/8.jpg", "n":"files/page/8.jpg",
"t":"files/thumb/8.jpg"},{"l":"files/page/9.jpg", "n":"files/page/9.jpg", "t":"files/thumb/9.jpg"},
{"l":"files/page/10.jpg", "n":"files/page/10.jpg", "t":"files/thumb/10.jpg"},{"l":"files/page/11.jpg",
"n":"files/page/11.jpg", "t":"files/thumb/11.jpg"},{"l":"files/page/12.jpg", "n":"files/page/12.jpg",
"t":"files/thumb/12.jpg"},{"l":"files/page/13.jpg", "n":"files/page/13.jpg", "t":"files/thumb/13.jpg"},
{"l":"files/page/14.jpg", "n":"files/page/14.jpg", "t":"files/thumb/14.jpg"},{"l":"files/page/15.jpg",
"n":"files/page/15.jpg", "t":"files/thumb/15.jpg"},{"l":"files/page/16.jpg", "n":"files/page/16.jpg",
"t":"files/thumb/16.jpg"},{"l":"files/page/17.jpg", "n":"files/page/17.jpg", "t":"files/thumb/17.jpg"},
{"l":"files/page/18.jpg", "n":"files/page/18.jpg", "t":"files/thumb/18.jpg"},{"l":"files/page/19.jpg",
"n":"files/page/19.jpg", "t":"files/thumb/19.jpg"},{"l":"files/page/20.jpg", "n":"files/page/20.jpg",
"t":"files/thumb/20.jpg"},{"l":"files/page/21.jpg", "n":"files/page/21.jpg", "t":"files/thumb/21.jpg"},
{"l":"files/page/22.jpg", "n":"files/page/22.jpg", "t":"files/thumb/22.jpg"},{"l":"files/page/23.jpg",
"n":"files/page/23.jpg", "t":"files/thumb/23.jpg"},{"l":"files/page/24.jpg", "n":"files/page/24.jpg",
"t":"files/thumb/24.jpg"},{"l":"files/page/25.jpg", "n":"files/page/25.jpg", "t":"files/thumb/25.jpg"},
{"l":"files/page/26.jpg", "n":"files/page/26.jpg", "t":"files/thumb/26.jpg"},{"l":"files/page/27.jpg",
"n":"files/page/27.jpg", "t":"files/thumb/27.jpg"},{"l":"files/page/28.jpg", "n":"files/page/28.jpg",
"t":"files/thumb/28.jpg"},{"l":"files/page/29.jpg", "n":"files/page/29.jpg", "t":"files/thumb/29.jpg"},
{"l":"files/page/30.jpg", "n":"files/page/30.jpg", "t":"files/thumb/30.jpg"},{"l":"files/page/31.jpg",
"n":"files/page/31.jpg", "t":"files/thumb/31.jpg"},{"l":"files/page/32.jpg", "n":"files/page/32.jpg",
"t":"files/thumb/32.jpg"},{"l":"files/page/33.jpg", "n":"files/page/33.jpg", "t":"files/thumb/33.jpg"},
{"l":"files/page/34.jpg", "n":"files/page/34.jpg", "t":"files/thumb/34.jpg"},{"l":"files/page/35.jpg",
"n":"files/page/35.jpg", "t":"files/thumb/35.jpg"},{"l":"files/page/36.jpg", "n":"files/page/36.jpg",
"t":"files/thumb/36.jpg"},{"l":"files/page/37.jpg", "n":"files/page/37.jpg", "t":"files/thumb/37.jpg"},
{"l":"files/page/38.jpg", "n":"files/page/38.jpg", "t":"files/thumb/38.jpg"},{"l":"files/page/39.jpg",
"n":"files/page/39.jpg", "t":"files/thumb/39.jpg"},{"l":"files/page/40.jpg", "n":"files/page/40.jpg",
"t":"files/thumb/40.jpg"}];
var language = [{language : "english",btnFirstPage : "First",btnNextPage : "Next",btnLastPage : "Last",
btnPrePage : "Previous",btnGoToHome : "Home",btnDownload : "Download",btnSoundOn : "Sound On",
btnSoundOff : "Sound Off",btnPrint : "Print",btnThumb : "Thumbnails",btnBookMark : "Bookmark",
frmBookMark : "Bookmark",btnZoomIn : "Zoom In",btnZoomOut : "Zoom Out",btnAutoFlip : "Auto Flip",
btnStopAutoFlip : "Stop Auto Flip",btnSocialShare : "Share",btnHelp : "Help",btnAbout : "About",
btnSearch : "Search",btnFullscreen : "Catalogo 2018",btnExitFullscreen : "Catalogo 2018",
btnMore : "Más",frmPrintCaption : "Print",frmPrintall : "Print All Pages",frmPrintcurrent : "Print Current Page",
frmPrintRange : "Print Range",frmPrintexample : "Example: 2,3,5-10",frmPrintbtn : "Print",frmShareCaption : "Share",
frmShareLabel : "Share",frmShareInfo : "",frminsertLabel : "",frminsertInfo : "",frmaboutcaption : "Contact",
frmaboutcontactinformation : "Contact Information",frmaboutADDRESS : "Address",frmaboutEMAIL : "Email",
frmaboutWEBSITE : "Website",frmaboutMOBILE : "Mobile",frmaboutAUTHOR : "Author",
frmaboutDESCRIPTION : "Description",frmSearch : "Search",frmToc : "Table Of Contents",
btnTableOfContent : "Table Of Contents",btnNote : "Annotation",lblLast : "Esta es la última página.",
blFirst : "Esta es la primera página.",lblFullscreen : "Catalogo 2018",
lblName : "Name",lblPassword : "Password",lblLogin : "Login",
lblCancel : "Cancel",lblNoName : "User name can not be empty.",lblNoPassword : "Password can not be empty.",
lblNoCorrectLogin : "Please enter the correct user name and password.",btnVideo : "Video Gallery",btnSlideShow : "Slideshow",
pnlSearchInputInvalid : "The search text is too short.",btnDragToMove : "Move by mouse drag",
btnPositionToMove : "Move by mouse position",lblHelp1 : "Drag the page corner to view",
lblHelp2 : "Double click to zoom in, out",lblCopy : "Copy",lblAddToPage : "Add To Page",lblPage : "Page",
lblTitle : "Title",lblEdit : "Edit",lblDelete : "Delete",lblRemoveAll : "Remove All",tltCursor : "Cursor",
tltAddHighlight : "Add highlight",tltAddTexts : "Add texts",tltAddShapes : "Add shapes",tltAddNotes : "Add notes",
tltAddImageFile : "Add image file",tltAddSignature : "Add signature",tltAddLine : "Add line",tltAddArrow : "Add arrow",
tltAddRect : "Add rect",tltAddEllipse : "Add ellipse",lblDoubleClickToZoomIn : "Double click to zoom in.",
lblPages : "Pages",infCopyToClipboard : "Your browser dose not support clipboard, please do it yourself.",
lblDescription : "Title",frmLinkLabel : "Link",infNotSupportHtml5 : "Your browser does not support HTML5.",
frmHowToUse : "How To Use",lblHelpPage1 : "Move your finger to flip the book page.",
lblHelpPage2 : "help2",
lblHelpPage3 : "help3",lblHelpPage4 : "help4",lblHelpPage5 : "help5",
frmQrcodeCaption : "",btnPageBack : "Backward",btnPageForward : "Forward",btnLanguage : "Change Language",
msgConfigMissing : "Configuration file is missing, unable to open the book.",btnPhoneNumber : "Tel",frmTelephone : "Tel",
btnDialing : "Call",lblSelectMessage : "Please copy the the text content in the text box.",btnSelectText : "Select Text",
DownloadCurrentPage : "Include Current Page"}];
var ols=[];
var bmtConfig = [];
var staticAd ={"haveAd":false, "interval":3000, "data":[]};
var videoList=[];
var slideshow =[];
var flipByAudio = {"audioType":0,"audioFile":"","showPlayer":false,"items":[]};
var phoneNumber = [];
var bookPlugin = null;
